name: Build Padavan firmware

on:
  workflow_dispatch:
    inputs:
      TARGET:
        description: 'Target device'
        required: true
        default: 'TL_C20-V5'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build firmware
        run: |
          curl -fsSL https://raw.githubusercontent.com/shvchk/padavan-builder/main/build.sh | \
          TARGET=${{ github.event.inputs.TARGET }} bash
